name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge,bioconda
        channel-priority: strict
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        environment-file: .test/environment.yaml
        activate-environment: test
    - name: Generate test data
      run: bash .test/generate_data.sh
    - name: snakemake
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: Snakefile
        args: "--use-conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache"
